apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: petclinic-image
spec:
  type: image
  params:
  - name: url
#    value: quay.io/siamaksade/spring-petclinic
    value: image-registry.openshift-image-registry.svc:5000/pipelines-demo/spring-petclinic