---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: webhook-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - name: petclinic-webhook
      binding:
        name: github-trigger-binding
      template:
        name: petclinic-trigger-template
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: webhook-listener
spec:
  port:
    targetPort: 8080
  to:
    kind: "Service"
    name: el-webhook-listener
    weight: 100
