---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: github-trigger-binding
spec:
  params:
  - name: gitrevision
    value: $(body.head_commit.id)
  - name: gitrepositoryurl
    value: $(body.repository.url)
  - name: contenttype
    value: $(header.Content-Type)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: petclinic-trigger-template
spec:
  params:
  - name: gitrevision
    description: The git revision
    default: master
  - name: gitrepositoryurl
    description: The git repository url
  - name: message
    description: The message to print
    default: This is the default message
  - name: contenttype
    description: The Content-Type of the event
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      generateName: petclinic-deploy-pipeline-run-
      labels:
        tekton.dev/pipeline: petclinic-deploy-pipeline
    spec:
      pipelineRef:
        name: petclinic-deploy-pipeline
      resources:
      - name: app-git
        resourceRef:
          name: petclinic-git
      - name: app-image
        resourceRef:
          name: petclinic-image
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: webhook-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - name: petclinic-webhook
      binding:
        name: github-trigger-binding
      template:
        name: petclinic-trigger-template
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: webhook-listener
spec:
  port:
    targetPort: 8080
  to:
    kind: "Service"
    name: el-webhook-listener
    weight: 100
