---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mvn-settings
data:
  .settings.xml: |
    <settings>
      <mirrors>
        <mirror>
          <id>bucketrepo</id>
          <name>bucketrepo- mirror</name>
          <url>http://mavenrepo:8080/bucketrepo/</url>
          <mirrorOf>*</mirrorOf>
        </mirror>
      </mirrors>
    </settings>
